[package]
name = "coursewatcher"
version = "0.2.0"
edition = "2024"
license = "AGPL-3"

[dependencies]
## Scraper side
log = "0.4"
thiserror = "2.0"
scraper = "0.23"
reqwest  = { version = "0.12", features = ["rustls-tls", "cookies", "http2", "system-proxy","blocking"], default-features = false }
anyhow = "1.0"

## Database and entrypoint
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["chrono", "hooks", "bundled"] }
env_logger = "0.11"

## For discord bot side
tokio = { version = "1.45", features = ["rt-multi-thread"] }
async-trait = "0.1"
serenity = "0.12"
